RUN pip install --no-cache-dir \
    torch==2.1.2 \
    transformers==4.39.3 \
    fastapi==0.110.0 \
    uvicorn==0.29.0 \
    huggingface_hub==0.21.4 \
    accelerate==0.28.0 \
    safetensors==0.4.2 \
    optimum==1.17.0